max-dist: 8
view-dist: 8
min-dist: 5
virtual-dist: 20
chunk-limit: 12000
up-interval: 300
down-interval: 30
stack-radius: 3
mobs-per-spawner: 60
spawner-check-interval: 30
stats-file: stats.txt
ticks-per-monster: 10
ticks-per-animal: 400
tps-threshold: 18.0
chunk-gc-interval: 200
chunk-rate: 50
chunk-rate-burst: 500
oreditor: 4
